setup travis to use mathcomp docker

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,43 +1,46 @@
 dist: trusty
 sudo: required
-language: c
-cache:
-  apt: true
-  directories:
-  - $HOME/opam
-addons:
-  apt:
-    sources:
-    - avsm
-    packages:
-    - opam
-    - aspcud
+language: generic
+
+services:
+  - docker
+
 env:
   global:
-  - NJOBS=2
-  # system is == 4.02.3
+  - NJOBS="2"
+  - CONTRIB_NAME="real-closed"
   matrix:
-  - COMPILER="system" MC_VERSION="1.7.0" COQ_VERSION="8.8.0"
+  - COQ_VERSION="8.7" MC_VERSION="1.7.0"
+  - COQ_VERSION="8.8" MC_VERSION="1.7.0"
 
-jobs:
-  include:
-    - stage: opam
-      script:
-      - mkdir -p ~/opam/
-      - opam init -j ${NJOBS} --root=~/opam/${COMPILER}-{$MC_VERSION} --compiler=${COMPILER} -n -y
-      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
-      - opam repo add coq-released http://coq.inria.fr/opam/released
-    - stage: coq
-      script:
-      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
-      - opam install -j ${NJOBS} -v -y coq.${COQ_VERSION}
-      - opam pin add coq ${COQ_VERSION}
-    - stage: math-comp
-      script:
-      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
-      - opam install -j ${NJOBS} -v -y coq-mathcomp-field.${MC_VERSION}
-      - opam pin add coq-mathcomp-field ${MC_VERSION}
-    - stage: real-closed
-      script:
-      - eval $(opam config --root=~/opam/${COMPILER}-{$MC_VERSION} env)
-      - make -j ${NJOBS}
+
+install: |
+  # Prepare the COQ container
+  docker pull "mathcomp/mathcomp:${MC_VERSION}-coq-${COQ_VERSION}"
+  docker run -d -i --init --name=COQ -v ${TRAVIS_BUILD_DIR}:/home/coq/${CONTRIB_NAME} -w /home/coq/${CONTRIB_NAME} "mathcomp/mathcomp:${MC_VERSION}-coq-${COQ_VERSION}"
+  docker exec COQ /bin/bash --login -c "
+    # This bash script is double-quoted to interpolate Travis CI env vars:
+    echo \"Build triggered by ${TRAVIS_EVENT_TYPE}\"
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
+    set -ex  # -e = exit on failure; -x = trace for debug
+    # Using flambda makes sense here as we usually get ~10% faster
+    # builds in math-comp.
+    eval $(opam env)
+    opam update -y
+    opam config list
+    opam repo list
+    opam list
+    "
+script:
+- echo -e "${ANSI_YELLOW}Building ${CONTRIB_NAME}...${ANSI_RESET}" && echo -en 'travis_fold:start:script\\r'
+- |
+  docker exec COQ /bin/bash --login -c "
+    export PS4='+ \e[33;1m(\$0 @ line \$LINENO) \$\e[0m '
+    set -ex
+    sudo chown -R coq:coq /home/coq/${CONTRIB_NAME}
+    eval $(opam env)
+    make -j "$NJOBS"
+    make install
+    "
+- docker stop COQ  # optional
+- echo -en 'travis_fold:end:script\\r'
